version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/apple/ios"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/apple/osx/hlidac shopu"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
